#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Thu Sep 14 08:17:21 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((754, 766))
        self.SetTitle("LNA Bias Diagnostic Ctrl")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_2.SetMinSize((802, 197))
        sizer_1.Add(self.panel_2, 1, wx.ALL | wx.EXPAND, 5)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.panel_2, wx.ID_ANY, "Pin Setting"), wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(4, 8, 2, 2)
        sizer_2.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 0")
        grid_sizer_1.Add(label_1, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 1")
        grid_sizer_1.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 2")
        grid_sizer_1.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 3")
        grid_sizer_1.Add(label_4, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 4")
        grid_sizer_1.Add(label_5, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 5")
        grid_sizer_1.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 6")
        grid_sizer_1.Add(label_7, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 7")
        grid_sizer_1.Add(label_8, 0, 0, 0)

        self.checkbox_1 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_1, 0, 0, 0)

        self.checkbox_2 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_2, 0, 0, 0)

        self.checkbox_3 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_3, 0, 0, 0)

        self.checkbox_4 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_4, 0, 0, 0)

        self.checkbox_5 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_5, 0, 0, 0)

        self.checkbox_6 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_6, 0, 0, 0)

        self.checkbox_7 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_7, 0, 0, 0)

        self.checkbox_8 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_8, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 8")
        grid_sizer_1.Add(label_9, 0, wx.ALL, 5)

        label_10 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 9")
        grid_sizer_1.Add(label_10, 0, wx.ALL, 5)

        label_11 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 10")
        grid_sizer_1.Add(label_11, 0, wx.ALL, 5)

        label_12 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 11")
        grid_sizer_1.Add(label_12, 0, wx.ALL, 5)

        label_13 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 12")
        grid_sizer_1.Add(label_13, 0, wx.ALL, 5)

        label_22 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 13")
        grid_sizer_1.Add(label_22, 0, wx.ALL, 5)

        label_23 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 14")
        grid_sizer_1.Add(label_23, 0, wx.ALL, 5)

        label_24 = wx.StaticText(self.panel_2, wx.ID_ANY, "Pin 15")
        grid_sizer_1.Add(label_24, 0, wx.ALL, 5)

        self.checkbox_9 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_9, 0, 0, 0)

        self.checkbox_10 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_10, 0, 0, 0)

        self.checkbox_11 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_11, 0, 0, 0)

        self.checkbox_12 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_12, 0, 0, 0)

        self.checkbox_13 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_13, 0, 0, 0)

        self.checkbox_14 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_14, 0, 0, 0)

        self.checkbox_15 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_15, 0, 0, 0)

        self.checkbox_16 = wx.CheckBox(self.panel_2, wx.ID_ANY, "En")
        grid_sizer_1.Add(self.checkbox_16, 0, 0, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_3.SetMinSize((802, 269))
        sizer_1.Add(self.panel_3, 1, wx.ALL | wx.EXPAND, 5)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.panel_3, wx.ID_ANY, "Wiper Settings"), wx.VERTICAL)

        grid_sizer_2 = wx.FlexGridSizer(5, 4, 0, 0)
        sizer_3.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_18 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_18, 0, wx.ALL, 10)

        label_19 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_19, 0, wx.ALL, 10)

        label_20 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_20, 0, wx.ALL, 10)

        label_21 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_21, 0, wx.ALL, 10)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_1.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_1, 0, wx.ALL | wx.EXPAND, 10)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_2.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_2, 0, wx.ALL | wx.EXPAND, 10)

        self.text_ctrl_3 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_3.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_3, 0, wx.ALL | wx.EXPAND, 10)

        self.text_ctrl_4 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_4.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_4, 0, wx.ALL | wx.EXPAND, 10)

        label_15 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_15, 0, wx.ALL, 10)

        label_14 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_14, 0, wx.ALL, 10)

        label_16 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_16, 0, wx.ALL, 10)

        label_17 = wx.StaticText(self.panel_3, wx.ID_ANY, "WIper N")
        grid_sizer_2.Add(label_17, 0, wx.ALL, 10)

        self.text_ctrl_5 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_5.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_5, 0, wx.ALL | wx.EXPAND, 10)

        self.text_ctrl_6 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_6.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_6, 0, wx.ALL | wx.EXPAND, 10)

        self.text_ctrl_7 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_7.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_7, 0, wx.ALL | wx.EXPAND, 10)

        self.text_ctrl_8 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "128")
        self.text_ctrl_8.SetMinSize((150, 34))
        grid_sizer_2.Add(self.text_ctrl_8, 0, wx.ALL | wx.EXPAND, 10)

        self.button_17 = wx.Button(self.panel_3, wx.ID_ANY, "Set Wipers")
        grid_sizer_2.Add(self.button_17, 0, wx.ALL, 10)

        self.text_ctrl_9 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "20230903-161500> Connected\n20230903-161501> Enabled Pin 0\n20230903-161502> Enabled Pin 2\n20230903-161503> Set Wiper 1 to 255\n20230903-161504> Ping\n20230903-161505> Enabled Pin 2\n20230903-161506> Enabled Pin 3\n20230903-161507> Set Wiper 2 to 255\n20230903-161508> Set Wiper 2 to 0\n20230903-161509> Set Wiper 2 to 255\n20230903-161510> Set Wiper 2 to 0", style=wx.HSCROLL | wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_WORDWRAP)
        self.text_ctrl_9.SetMinSize((812, 150))
        sizer_1.Add(self.text_ctrl_9, 0, wx.EXPAND, 0)

        self.panel_3.SetSizer(sizer_3)

        self.panel_2.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class BiasDiag(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class BiasDiag

if __name__ == "__main__":
    BiasDiag = BiasDiag(0)
    BiasDiag.MainLoop()
